Repository HexCorpProgramming/HexCorpDiscordAI, pull requests merged in 2020-12, with the labels that each got.

#189 Replaced all references of 0006 in storage with "Hive Mxtress"
  ai/storage.py
  test/test_storage.py
Labels: Feature Amendment

#188 Optimization disabled in mod channels
  ai/speech_optimization.py
  channels.py
  test/test_speech_optimization.py
Labels: Feature Amendment

#184 optimization/glitched/prepending are not removed when a drone enters
  ai/storage.py
  roles.py
  test/test_storage.py
Labels: Bug

#183 replaced role check with DB check
  ai/speech_optimization.py
  test/test_speech_optimization.py
Labels: Bug

#187 Feature/add ack and welcome codes
  ai/speech_optimization.py
Labels: Feature Amendment

#191 Associates can no longer use status codes
  ai/speech_optimization.py
  db/drone_dao.py
  test/test_speech_optimization.py
Labels: Bug

#204 Feature/no thinking
  .flake8
  ai/amplifier.py
  ai/assign.py
  ai/data_objects.py
  ai/glitch_message.py
  ai/id_prepending.py
  ai/identity_enforcement.py
  ai/join.py
  ai/respond.py
  ai/speech_optimization.py
  ai/stoplights.py
  ai/storage.py
  ai/thought_denial.py
  main.py
  test/test_amplifier.py
  test/test_speech_optimization.py
  test/test_thought_denial.py
  test/test_webhook.py
  webhook.py
Labels: Architecture, Feature Amendment, New Feature
